### ISSUE TITLE
Can't easily see the data in the database

### ISSUE THREAD

**Issue by alberttwong** [elovation/elovation#130]

**Comment by alberttwong** [comment]
modify docker-compose.yml to add database port forward

```
albert@albertonehouse elovation % cat docker-compose.yml
services:
  db:
    ports:
      - 5432:5432
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/elovation
    ports:
      - "4321:3000"
    depends_on:
      - db
  ```
